Feat/add docstrings
nitrictech/jvm-sdk pull request #2
Opened 2022-10-25 00:02 UTC by HomelessDinosaur

2022-10-25 00:53 UTC, asalkeld approved these changes

2022-10-25 05:36 UTC, tjholm approved these changes

2022-10-25 05:37 UTC, tjholm requested changes
@HomelessDinosaur can we target develop for this?

2022-11-01 02:35 UTC, tjholm submitted a review, later dismissed

2022-11-01 02:35 UTC, tjholm commented on .github/workflows/publish.yaml
> +          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
Let's try jitpack releases first.

2023-08-21 02:54 UTC, closed without merging